<a href="https://colab.research.google.com/github/parkmicheal1114/study/blob/main/study/numpy%EC%8B%A4%EC%8A%B5_%EC%98%88%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import matplotlib.pyplot as plt

- 원소가 모두 0이고 크기가 10인 numpy array를 생성하는 코드를 작성해보세요

In [5]:
np.zeros(10) # 배열을 초기화 한다고 생각 해보자

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

- 원소가 모두 32bytes 사이즈의 float 타입을 가지는 numpy array를 생성하는 코드를 작성해보세요.



``` python
#output
array([1.1, 2.2, 3.3, -4.4, 5.5], dtype=np.float32)
```

In [15]:
L = [1.1, 2.2, 3.3, -4.4, 5.5]
arr = np.array(L , dtype='float32')
arr

array([ 1.1,  2.2,  3.3, -4.4,  5.5], dtype=float32)

-1부터 1000까지의 모든 정수를 원소로 하는 numpy array를 생성하는 코드를 작성해보세요.

In [19]:
np.arange(0,1.1,0.1)


array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [24]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

- numpy 라이브러리의 numpy array가 가질 수 있는 data type을 모두 서술해보세요.

> 불리언 ( 'b' ) , 정수 ( 'i' ) , 부호 없는 정수 ( 'u' ) , 실수 ( 'f' ) , 복소수 ( 'c' ) , 객체 ( 'O' ) , 바이트 문자열( 'S' ) , 유니코드 문자열('U')



- numpy array 내에서의 모든 원소가 1) 동일한 data type을 가져야 하는 이유와, 2) 동일한 data type을 가지는 것으로 python list에 비해 갖게되는 장점에 대해 서술해보세요.

> numpy는 수치계산에 특화된 라이브러리입니다.

> 대부분의 수치 계산에 사용되는 데이터는 벡터(vector)이고, 이 벡터를 표현한게 numpy array입니다.

> 벡터의 원소들은 기본적으로 정해진 vectro space에 표현됩니다. 이 vector space를 정의하면 나타나는 숫자의 표현 범위도 정해집니다.

> 정해진 표현 범위에서 효율적인 연산을 하기 위해서는 data type이 통일될 필요가 있습니다.

> data type이 통일되면 operator를 이용한 연산을 할 때, type checking할 필요가 없어지면서 시간상 이득이 있습니다.

> 이를 효과적으로 이용한 것이 바로 Numpy가 제공하는 Universal Function이나 Broadcasting입니다


- 주어진 numpy array의 두번째 원소를 찾아서 출력하는 코드를 작성해보세요

In [25]:
arr = np.array([31, 24, 37, 14, 25])
arr[1]

24

- 주어진 다차원 numpy array에서 두번째 행의 세번째 원소를 찾는 코드를 작성해보세요.

In [26]:
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2[1,2]

6

- 주어진 2차원 numpy array는 행렬을 나타냅니다.
주어진 행렬에서 첫번째 행과, 두번째 열을 출력하는 코드를 작성해보세요.

> FANCY INDEXING

In [29]:
arr2 = np.array([ [10, 9, 8], [7, 6, 5], [4, 3, 2] ])
arr2[0,:] , arr2[:,1]

(array([10,  9,  8]), array([9, 6, 3]))

- 주어진 numpy array 에 대해서, 30보다 큰 숫자만 뽑는 코드를 작성하세요.
(단, 반복문을 통한 방법이 아닌 numpy array masking을 사용하세요.

> array masking

> 익숙해 지면 좋음 (https://spacecollection.co.kr/8)

In [37]:
arr = np.array([30, 4, 550, 9, 112, 10000, 15, 21])
arr[arr>30]

array([  550,   112, 10000])

- 주어진 numpy array의 최소/최대값을 찾아서 출력하는 코드를 작성해보세요.

In [45]:
arr = np.array([50, 1110, 1, 230, 3, 40, 517590, -41, -4959])
print(f"min : {arr.min()} \nMax : {arr.max()}" )

min : -4959 
Max : 517590


- 주어진 numpy array의 최소값과 최대값에 해당하는 원소의 index를 찾아서 출력하는 코드를 작성해보세요.

In [46]:
arr = np.array([1, 33, 5502, 221, -591, 0, -9, 50491])

print(f"index of min : {arr.argmin()} \nindex of Max : {arr.argmax()}")

index of min : 4 
index of Max : 7


- 주어진 두 개의 numpy array를 하나로 합치는 코드를 작성하세요.

```python
array([1, 2, 3, 4, 5, 6, 7, 8, 9])
```



In [50]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9])

np.concatenate([arr1,arr2],axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

- 주어진 1차원 numpy array 3개를 연결하여, 하나의 행렬을 구성하는 코드를 작성하세요.

```python
array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
```

In [54]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

np.vstack([arr1,arr2,arr3])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

- 두개의 벡터 v1,v2가 numpy array로 주어졌을 때, 두 벡터의 합 v1+v2 을 구하는 코드를 작성하세요.

In [55]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, -1, 2])

v1+v2

array([5, 1, 5])

-두개의 벡터 v1,v2가 numpy array로 주어졌을 때, 두 벡터의 내적 v1⋅v2 을 구하는 코드를 작성하세요.

In [62]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, -1, 2])

np.dot(v1,v2)

8

- 주어진 numpy array의 모든 원소에 각각 3을 더하는 코드를 작성하세요.

In [63]:
arr1 = np.array([1, 2, 3])

arr1 + 3

array([4, 5, 6])

- numpy array로 표현된 행렬에 모든 행에 같은 벡터를 더하는 연산을 수행하는 코드를 작성하세요.

In [64]:
mat1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
v1 = np.array([-1, -2, -3])

mat1 + v1 

array([[0, 0, 0],
       [3, 3, 3],
       [6, 6, 6]])

- 이미지 데이터를 처리할 때, numpy array를 통해서 이미지 데이터를 표현하면 "가로 pixel X 세로 pixel" 크기의 numpy array가 됩니다.
5x5의 크기를 가지는 이미지가 numpy array로 표현되었을 때, 이를 1차원 벡터로 변환하는 코드를 작성해보세요

In [70]:
img = np.random.randint(0,20,(5, 5))
print(img)
print()
img.flatten()

[[ 7  2 19  9 12]
 [ 5  7  9  1  5]
 [12  1 14 14  1]
 [15 14  4 18  1]
 [12  3  5 14  7]]



array([ 7,  2, 19,  9, 12,  5,  7,  9,  1,  5, 12,  1, 14, 14,  1, 15, 14,
        4, 18,  1, 12,  3,  5, 14,  7])